'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { getDiagnostics, clearDiagnostics } from '@/lib/api';
import DiagnosticCard from '@/components/DiagnosticCard';

export default function DiagnosticsListPage() {
  const [diagnostics, setDiagnostics] = useState([]);
  const [loading, setLoading] = useState(true);
  const [clearing, setClearing] = useState(false);
  const [fixes, setFixes] = useState([]);

  // Load fixes from localStorage to hide already fixed diagnostics
  useEffect(() => {
    const loadFixes = () => {
      try {
        const stored = JSON.parse(localStorage.getItem('runtime-agent-fixes') || '[]');
        setFixes(stored);
      } catch { setFixes([]); }
    };
    loadFixes();
    const handleStorage = (e) => {
      if (e.key === 'runtime-agent-fixes' || e.type === 'fixes-updated') loadFixes();
    };
    window.addEventListener('storage', handleStorage);
    window.addEventListener('fixes-updated', handleStorage);
    return () => {
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('fixes-updated', handleStorage);
    };
  }, []);

  const fetchDiagnostics = useCallback(async () => {
    try {
      const data = await getDiagnostics();
      setDiagnostics(data);
    } catch (err) {
      console.error('Failed to fetch diagnostics:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const initialRefresh = setTimeout(fetchDiagnostics, 0);
    const fallbackRefresh = setInterval(fetchDiagnostics, 60000);
    const wsUrl = process.env.NEXT_PUBLIC_WS_URL || 'ws://localhost:8000/api/ws';
    const ws = new WebSocket(wsUrl);

    ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data);
        if (msg.type === 'diagnostic_completed') {
          const diagnostic = msg.data;
          setDiagnostics((prev) => [
            diagnostic,
            ...prev.filter((item) => item.id !== diagnostic.id && item.anomaly_id !== diagnostic.anomaly_id),
          ]);
          setLoading(false);
        }
      } catch (err) {
        console.error('Failed to parse WebSocket message:', err);
      }
    };

    return () => {
      clearTimeout(initialRefresh);
      clearInterval(fallbackRefresh);
      ws.close();
    };
  }, [fetchDiagnostics]);

  const handleClear = async () => {
    if (!confirm('Are you sure you want to clear all diagnostics?')) return;
    setClearing(true);
    try {
      await clearDiagnostics();
      await fetchDiagnostics();
    } catch (e) {
      console.error('Failed to clear:', e);
    } finally {
      setClearing(false);
    }
  };

  return (
    <div className="container">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title">AI Diagnostics</h1>
          <p className="page-subtitle">Autonomous root-cause analysis reports generated by the AI agent</p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <span className="badge badge-info">
            {diagnostics.filter((diag) => !fixes.some((f) => f.id === diag.id || f.id === diag.anomaly_id)).length} Reports
          </span>
          {diagnostics.length > 0 && (
            <button 
              className="btn btn-secondary" 
              onClick={handleClear} 
              disabled={clearing}
              style={{ background: 'rgba(248, 81, 73, 0.1)', color: '#f85149', borderColor: 'rgba(248, 81, 73, 0.3)' }}
            >
              {clearing ? 'Clearing...' : 'Clear All'}
            </button>
          )}
        </div>
      </div>

      <div style={{ marginTop: '24px' }}>
        {(() => {
          const visibleDiagnostics = diagnostics.filter((diag) => !fixes.some((f) => f.id === diag.id || f.id === diag.anomaly_id));
          
          if (loading) {
            return (
          <div className="diagnostics-grid">
            {[1, 2, 3].map((i) => (
              <div key={i} className="diagnostic-card">
                <div className="loading-shimmer" style={{ height: '20px', width: '30%', marginBottom: '12px', borderRadius: '6px' }} />
                <div className="loading-shimmer" style={{ height: '16px', width: '80%', marginBottom: '8px', borderRadius: '6px' }} />
                <div className="loading-shimmer" style={{ height: '16px', width: '60%', borderRadius: '6px' }} />
              </div>
            ))}
          </div>
          );
        }

        if (visibleDiagnostics.length === 0) {
          return (
          <div className="empty-state-large">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-secondary)" strokeWidth="1">
              <circle cx="12" cy="12" r="10" />
              <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
              <line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
            <h3>No Diagnostics Available</h3>
            <p>AI diagnostic reports will appear here when the monitoring agent detects new anomalies. Any diagnostics with applied fixes have been hidden.</p>
            <Link href="/" className="btn btn-secondary">
              ← Back to Dashboard
            </Link>
          </div>
          );
        }

        return (
          <div className="diagnostics-grid">
            {visibleDiagnostics.map((diag, index) => (
              <div key={diag.id} className={`animate-slide-up animate-delay-${Math.min(index + 1, 4)}`}>
                <DiagnosticCard
                  diagnostic={diag}
                  href={`/diagnostics/${diag.id}`}
                />
              </div>
            ))}
          </div>
        );
        })()}
      </div>
    </div>
  );
}
