'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { getDiagnostics, clearDiagnostics } from '@/lib/api';
import DiagnosticCard from '@/components/DiagnosticCard';
import { useRouter } from 'next/navigation';

export default function DiagnosticsListPage() {
  const [diagnostics, setDiagnostics] = useState([]);
  const [loading, setLoading] = useState(true);
  const [clearing, setClearing] = useState(false);
  const router = useRouter();

  const fetchDiagnostics = async () => {
    try {
      const data = await getDiagnostics();
      setDiagnostics(data);
    } catch (err) {
      console.error('Failed to fetch diagnostics:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDiagnostics();
    const interval = setInterval(fetchDiagnostics, 10000);
    return () => clearInterval(interval);
  }, []);

  const handleClear = async () => {
    if (!confirm('Are you sure you want to clear all diagnostics?')) return;
    setClearing(true);
    try {
      await clearDiagnostics();
      await fetchDiagnostics();
    } catch (e) {
      console.error('Failed to clear:', e);
    } finally {
      setClearing(false);
    }
  };

  return (
    <div className="container">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title">AI Diagnostics</h1>
          <p className="page-subtitle">Autonomous root-cause analysis reports generated by the AI agent</p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <span className="badge badge-info">{diagnostics.length} Reports</span>
          {diagnostics.length > 0 && (
            <button 
              className="btn btn-secondary" 
              onClick={handleClear} 
              disabled={clearing}
              style={{ background: 'rgba(248, 81, 73, 0.1)', color: '#f85149', borderColor: 'rgba(248, 81, 73, 0.3)' }}
            >
              {clearing ? 'Clearing...' : 'Clear All'}
            </button>
          )}
        </div>
      </div>

      <div style={{ marginTop: '24px' }}>
        {loading ? (
          <div className="diagnostics-grid">
            {[1, 2, 3].map((i) => (
              <div key={i} className="diagnostic-card">
                <div className="loading-shimmer" style={{ height: '20px', width: '30%', marginBottom: '12px', borderRadius: '6px' }} />
                <div className="loading-shimmer" style={{ height: '16px', width: '80%', marginBottom: '8px', borderRadius: '6px' }} />
                <div className="loading-shimmer" style={{ height: '16px', width: '60%', borderRadius: '6px' }} />
              </div>
            ))}
          </div>
        ) : diagnostics.length === 0 ? (
          <div className="empty-state-large">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="var(--color-text-secondary)" strokeWidth="1">
              <circle cx="12" cy="12" r="10" />
              <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
              <line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
            <h3>No Diagnostics Generated Yet</h3>
            <p>AI diagnostic reports will appear here when the monitoring agent detects and analyzes performance anomalies in your application.</p>
            <Link href="/" className="btn btn-secondary">
              ← Back to Dashboard
            </Link>
          </div>
        ) : (
          <div className="diagnostics-grid">
            {diagnostics.map((diag, index) => (
              <div key={diag.id} className={`animate-slide-up animate-delay-${Math.min(index + 1, 4)}`}>
                <DiagnosticCard
                  diagnostic={diag}
                  onClick={() => router.push(`/diagnostics/${diag.id}`)}
                />
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
